//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateOrder { get; set; }
        public Nullable<double> Cost { get; set; }
        public string WebName { get; set; }
        public string TrackingNumber { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<byte> Provided { get; set; }
    }
}
